source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target ‘testWeatherSw’ do    
       pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3-rebased'
       pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git', :branch => 'swift3'
       pod 'MBProgressHUD', '~> 0.9.2'
       #  pod 'ProgressKit', :git => 'https://github.com/kaunteya/ProgressKit.git', :branch => 'swift-3'
       pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
       pod 'SWSegmentedControl'
       pod 'SRKControls'
end


target 'testWeatherSwTests' do

end

target 'testWeatherSwUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
