source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target ‘testWeatherSw’ do
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'Alamofire', '~> 3.0'
	pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SRKControls', '~> 3.0.1'
    pod 'SevenSwitch', '~> 2.0'
end


target 'testWeatherSwTests' do

end

target 'testWeatherSwUITests' do

end
